// daostinations.ts

export const daostinations = [
  { id: 1, name: "AO Summit in Charleston, SC" },
  { id: 2, name: "Golf Getaway at Spey Bay" },
  { id: 3, name: "Crypto Retreat in Seoul" },
  { id: 4, name: "DeFi Condo in Dubai" },
  { id: 5, name: "NFT Summit in New York" },
  { id: 6, name: "Crypto Gathering in Austin" },
  { id: 7, name: "Alpine Escape: Canadian Mountain Lodge" },
  { id: 8, name: "Safari Serenity: African Expedition" },
  { id: 9, name: "Into the Wild: Yellowstone Adventure" },
  { id: 10, name: "Snowy Retreat: Swiss Chalet Getaway" },
  { id: 11, name: "Ethereum Retreat in Prague" },
  { id: 12, name: "City Lights: New York Penthouse Retreat" },
  { id: 13, name: "Riverside Retreat: Amazon Jungle Lodge" },
  { id: 14, name: "Urban Exploration: Tokyo High-Rise Apartment" },
  { id: 15, name: "Cultural Immersion: Kyoto Ryokan Experience" },
  { id: 16, name: "On a boat!" },
  { id: 17, name: "Bitcoin Beach Bash!" },
  { id: 18, name: "Desert Oasis: Moroccan Riad Retreat" },
  { id: 19, name: "Coastal Charm: Italian Seaside Villa" },
  { id: 20, name: "Sunset Serenade: Greek Island Villa" },
  { id: 21, name: "Tropical Paradise: Caribbean Beachfront Villa" },
];
